language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules

after_success:
  - pwd

deploy:  
  - provider: lambda
    function_name: "lambda-879"
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    region: "us-east-1"
    role: "arn:aws:iam::$account_no:role/LambdaExecutor"
    runtime: "nodejs6.10"
    handler_name: "handler"
    on:
     branch: master
     
script:
  - pwd
  - ls -al
